name: DP-Lotto
version: 1.0.0.2
main: com.darksoldier1404.dlt.Lotto
authors: [ DEAD_POOLIO_ ]
depend:
  - DPP-Core
commands:
  로또:
    permission: dlt.buy
    aliases: [ dlt ]
    description: 로또를 구매하거나 조회합니다.
  dlta:
    permission: dlt.admin
    aliases: [ dltadmin ]
    description: 로또 관리자 명령어 입니다.
